/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BtnGoogleLogin: typeof import('./components/BtnGoogleLogin.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablaEstCur: typeof import('./components/tablaEstCur.vue')['default']
    TablaProfCur: typeof import('./components/tablaProfCur.vue')['default']
  }
}
